name: Binta
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  animated_splash_screen: ^1.0.1+2
  #firebase_auth: ^0.20.0+1
  #firebase_core: ^0.7.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2
  get: ^4.6.5
  #google_sign_in: ^4.5.9
  provider: ^6.0.5
  contacts_service: ^0.6.3
  permission_handler: ^10.4.3
  shared_preferences: ^2.2.0

  #flutter_dialogflow: ^0.1.3
  bubble: ^1.1.9+1
  intl: ^0.18.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "lib/shared/assets/images/binta_logo_full.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - lib/shared/assets/images/

